### ISSUE TITLE
Feature Request: Deploy on GitHub Pages

### ISSUE THREAD

**Issue by MilanDonhowe** [andregumieri/spotify-for-all#3]
Once this project gets more developed a easy way to make it more accessible for non-tech-savvy folk would be to just deploy the website on GitHub's free website hosting service.  You can read more about githubPages [here](https://pages.github.com/).

**Comment by andregumieri** [comment]
Awesome. I even already registered the domain for it. 

And I'm talking to other developers so we can make it as dynamic as possible. We will be creating a back-end so people can create their own versions of artists an music :)

**Comment by andregumieri** [comment]
@MilanDonhowe https://listen.musicforall.app/

Now we have @rflgentil and @otaviobaldan working to make a web app to dynamically create these collections of albums so everyone can personalize your own :)

Thanks for your support
